/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#70103b",
        "on-primary-fixed-variant": "#32008a",
        "inverse-primary": "#6834eb",
        "primary-dim": "#7e51ff",
        "background": "#0e0e0e",
        "primary": "#b6a0ff",
        "surface-container-low": "#131313",
        "surface-tint": "#b6a0ff",
        "on-primary-container": "#280072",
        "surface-container": "#1a1a1a",
        "primary-container": "#a98fff",
        "on-secondary-fixed-variant": "#00655b",
        "on-secondary-fixed": "#00463f",
        "on-error-container": "#ffb2b9",
        "surface-bright": "#2c2c2c",
        "on-primary-fixed": "#000000",
        "secondary-container": "#006a60",
        "tertiary-fixed": "#ff8db2",
        "surface-dim": "#0e0e0e",
        "surface-container-lowest": "#000000",
        "on-surface-variant": "#adaaaa",
        "outline": "#767575",
        "primary-fixed": "#a98fff",
        "surface-container-high": "#20201f",
        "on-tertiary-container": "#59002b",
        "error": "#ff6e84",
        "on-primary": "#340090",
        "tertiary": "#ff97b8",
        "on-secondary-container": "#dcfff8",
        "secondary-fixed": "#4af8e3",
        "on-secondary": "#005b51",
        "on-background": "#ffffff",
        "secondary-dim": "#33e9d5",
        "secondary-fixed-dim": "#33e9d5",
        "surface": "#0e0e0e",
        "error-dim": "#d73357",
        "inverse-surface": "#fcf9f8",
        "on-surface": "#ffffff",
        "on-error": "#490013",
        "on-tertiary": "#6a0936",
        "tertiary-fixed-dim": "#f57ca5",
        "tertiary-dim": "#ef77a0",
        "outline-variant": "#484847",
        "secondary": "#4af8e3",
        "primary-fixed-dim": "#9c7eff",
        "on-tertiary-fixed": "#380019",
        "tertiary-container": "#fc81ab",
        "error-container": "#a70138",
        "inverse-on-surface": "#565555",
        "surface-variant": "#262626",
        "surface-container-highest": "#262626"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
